export const CompanyColumns = [
  {
    id: "actions",
    title: "Actions",
    web1: "20px",
    web2: "text-[25px]",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "name",
    title: "Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "email",
    title: "Email",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "contact",
    title: "Contact",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "cnic",
    title: "CNIC",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "description",
    title: "Description",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "address",
    title: "Address",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "branch",
    title: "Branch",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "total",
    title: "Total",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "paid",
    title: "Paid",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "remaining",
    title: "Payable",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
