export const CompleteLedgerColumns = [
  {
    id: "date",
    title: "Date",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "desc",
    title: "Description",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "dr",
    title: "Debit",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "cr",
    title: "Credit",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "bal",
    title: "Closing Balance",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
