export const CustomerColumns = [
  {
    id: "actions",
    title: "Actions",
    web1: "20px",
    web2: "text-[25px]",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "name",
    title: "Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "email",
    title: "Email",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  // {
  //   id: "password",
  //   title: "Password",
  //   web1: "20px",
  //   web2: "25px",
  //   web3: "30px",
  //   web4: "35px",
  // },
  // {
  //   id: "user_type",
  //   title: "User Type",
  //   web1: "20px",
  //   web2: "25px",
  //   web3: "30px",
  //   web4: "35px",
  // },
  {
    id: "cnic",
    title: "CNIC",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "contact",
    title: "Contact",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "address",
    title: "Address",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "branch",
    title: "Branch",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "ref",
    title: "Reference",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "page",
    title: "Page",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "total",
    title: "Total",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "return_amount",
    title: "Return Amount",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "opening_balance",
    title: "Opening Balance",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "discount",
    title: "Discount",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "paid",
    title: "Recieved",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "remaining",
    title: "Recievable",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "date",
    title: "Date",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
