export const InvoiceEditColumns = [
  {
    id: "actions",
    align: "center",
    title: "Actions",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "article_name",
    title: "Article",
    align: "center",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "article_size",
    title: "Size",
    align: "center",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "qty",
    title: "Quantity",
    align: "center",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },

  {
    id: "price",
    title: "Price",
    align: "center",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "amount",
    title: "Amount",
    align: "center",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
