export const ItemColumns = [
  {
    id: "actions",
    title: "Actions",
    web1: "20px",
    web2: "text-[25px]",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "branch_name",
    title: "Branch Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "article_name",
    title: "Article",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "size",
    title: "Size",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "purchase",
    title: "Purchase",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "sale",
    title: "Sale",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "in_qty",
    title: "In Qty",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "out_qty",
    title: "Out Qty",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "qty",
    title: "Qty",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "branch",
    title: "Branch",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
