export const RM_Stat_Columns = [
  {
    id: "actions",
    title: "Actions",
    web1: "20px",
    web2: "text-[25px]",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "branch_name",
    title: "Branch Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  //   {
  //     id: "branch",
  //     title: "Branch Number",
  //     web1: "20px",
  //     web2: "25px",
  //     web3: "30px",
  //     web4: "35px",
  //   },
  {
    id: "supplier_name",
    title: "Supplier Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "rm_name",
    title: "Raw Material Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "purchase",
    title: "Purchase Amount",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "qty",
    title: "Quantity",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "total_amount",
    title: "Total Amount",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "invoice_no",
    title: "Invoice #",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "truck_no",
    title: "Truck #",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "date",
    title: "Date",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "desc",
    title: "Description",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
